export const MOVIES_LOADED = 'MOVIES_LOADED';
export const START_MOVIES_LOADING = 'START_MOVIES_LOADING';
export const STOP_MOVIES_LOADING = 'STOP_MOVIES_LOADING';
export const ERROR_MOVIES_LOADING = 'ERROR_LOADING_MOVIES';

export const MOVIES_SORT_BY_VOTE_AVEREGE_FROM_MAX = 'MOVIES_SORT_BY_VOTE_AVEREGE_FROM_MAX';
export const MOVIES_SORT_BY_DEFAULT = 'MOVIES_SORT_BY_DEFAULT';
export const MOVIES_SORT_BY_TITLE = 'MOVIES_SORT_BY_TITLE';
export const MOVIES_SORT_BY_RELEASE_DATE_FROM_MIN = 'MOVIES_SORT_BY_RELEASE_DATE_FROM_MIN';
export const MOVIES_SORT_BY_POPULARITY_FROM_MAX = 'MOVIES_SORT_BY_POPULARITY_FROM_MAX';

export const MOVIES_GENRES_LOADED = 'MOVIES_GENRES_LOADED';
export const START_GENRES_LOADING = 'START_GENRES_LOADING';
export const STOP_GENRES_LOADING = 'STOP_GENRES_LOADING';
export const ERROR_MOVIES_GENRES_LOADING = 'ERROR_MOVIES_GENRES_LOADING';
